(define-library (storkar player-db)
  (import (chibi) (chibi filesystem) (chibi config)
          (presto config) (presto alist) (presto fileutils))
  (export player-db-initialize player-db-initialized? get-all-players get-player set-player delete-player)
  (include "player-db.scm"))
