(define-library (storkar player-db)
  (import (chibi)
          (chibi config)
          (chibi filesystem)
          (presto alist)
          (presto config)
          (presto fileutils)
          (presto uuid))
  (export player-db-initialize player-db-initialized? get-all-players get-player set-player delete-player)
  (include "player-db.scm"))
