(define-library (storkar sexp-db-rest-wrapper)
  (import (chibi)
          (chibi string)
          (presto alist)
          (presto json)
          (presto request)
          (presto uuid)
          (storkar sexp-db))
  (export make-sexp-db-rest-wrapper)
  (include "sexp-db-rest-wrapper.scm"))
