(define-library (storkar team-db)
  (import (chibi)
          (chibi filesystem)
          (chibi config)
          (presto alist)
          (presto config)
          (presto fileutils)
          (presto uuid))
  (export team-db-initialize team-db-initialized? get-all-teams get-team set-team delete-team)
  (include "team-db.scm"))
